export const types = Object.freeze({
  // Sync
  NEWS_START_FETCHING: 'NEWS_START_FETCHING',
  NEWS_STOP_FETCHING: 'NEWS_STOP_FETCHING',
  NEWS_FILL: 'NEWS_FILL',
  NEWS_SET_FETCHING_ERROR: 'NEWS_SET_FETCHING_ERROR',

  // Async
  NEWS_FETC_ASYNC: 'NEWS_FETC_ASYNC',
});